{
 "cells": [
  {
   "metadata": {},
   "cell_type": "code",
   "outputs": [],
   "execution_count": null,
   "source": [
    "import os\n",
    "import textwrap\n",
    "\n",
    "webrtc_src_dir = os.path.join(os.getcwd(), \"webrtc_build\", \"src\")\n",
    "wrapper_dir = os.path.join(webrtc_src_dir, \"ffm_wrapper\")\n",
    "os.makedirs(wrapper_dir, exist_ok=True)"
   ],
   "id": "a19f8ef83a0c06ac"
  },
  {
   "metadata": {},
   "cell_type": "code",
   "outputs": [],
   "execution_count": null,
   "source": [
    "header_content = textwrap.dedent(\"\"\"\\\n",
    "    #pragma once\n",
    "    #include <stdint.h>\n",
    "    #include <stdbool.h>\n",
    "\n",
    "    #if defined(_WIN32)\n",
    "    #define FFM_EXPORT __declspec(dllexport)\n",
    "    #else\n",
    "    #define FFM_EXPORT\n",
    "    #endif\n",
    "\n",
    "    #ifdef __cplusplus\n",
    "    extern \"C\" {\n",
    "    #endif\n",
    "\n",
    "    // --- Audio Processing ---\n",
    "    typedef void* FFM_AudioProcessing;\n",
    "    FFM_EXPORT FFM_AudioProcessing FFM_CreateAudioProcessing();\n",
    "    FFM_EXPORT void FFM_FreeAudioProcessing(FFM_AudioProcessing apm);\n",
    "    FFM_EXPORT void FFM_ApplyAudioProcessingConfig(FFM_AudioProcessing apm,\n",
    "        bool ns_enabled, int ns_level,\n",
    "        bool aec_enabled, bool aec_hp_filter,\n",
    "        bool hp_enabled,\n",
    "        bool gc_enabled, int gc_fixed_gain_db,\n",
    "        bool agc_enabled, int agc_target_level, int agc_max_gain, int agc_max_noise, int agc_step);\n",
    "    FFM_EXPORT void FFM_SetStreamDelayMs(FFM_AudioProcessing apm, int delay_ms);\n",
    "    FFM_EXPORT int FFM_ProcessStream(FFM_AudioProcessing apm, const int16_t* src, int sample_rate_in, int channels, int16_t* dest);\n",
    "\n",
    "    // --- VAD ---\n",
    "    typedef void* FFM_Vad;\n",
    "    FFM_EXPORT FFM_Vad FFM_CreateVad();\n",
    "    FFM_EXPORT void FFM_FreeVad(FFM_Vad vad);\n",
    "    FFM_EXPORT int FFM_InitVad(FFM_Vad vad);\n",
    "    FFM_EXPORT int FFM_SetVadMode(FFM_Vad vad, int mode);\n",
    "    FFM_EXPORT int FFM_ProcessVad(FFM_Vad vad, int sample_rate, const int16_t* audio_frame, size_t frame_length);\n",
    "\n",
    "    // --- Resampler ---\n",
    "    typedef void* FFM_Resampler;\n",
    "    FFM_EXPORT FFM_Resampler FFM_CreateResampler();\n",
    "    FFM_EXPORT void FFM_FreeResampler(FFM_Resampler resampler);\n",
    "    FFM_EXPORT int FFM_Resample(FFM_Resampler resampler, const int16_t* src, size_t src_length, int src_rate, int16_t* dest, size_t dest_capacity, int dest_rate, int channels);\n",
    "\n",
    "    #ifdef __cplusplus\n",
    "    }\n",
    "    #endif\n",
    "    \"\"\")\n",
    "\n",
    "with open(os.path.join(wrapper_dir, \"webrtc_ffm.h\"), \"w\") as f:\n",
    "    f.write(header_content)"
   ],
   "id": "bbaaff7bf07c53c"
  },
  {
   "metadata": {},
   "cell_type": "code",
   "outputs": [],
   "execution_count": null,
   "source": [
    "cpp_content = textwrap.dedent(\"\"\"\\\n",
    "    #include \"webrtc_ffm.h\"\n",
    "    #include \"modules/audio_processing/include/audio_processing.h\"\n",
    "    #include \"common_audio/vad/include/webrtc_vad.h\"\n",
    "    #include \"common_audio/resampler/include/push_resampler.h\"\n",
    "    #include \"api/audio/audio_frame.h\"\n",
    "\n",
    "    using namespace webrtc;\n",
    "\n",
    "    extern \"C\" {\n",
    "\n",
    "    FFM_AudioProcessing FFM_CreateAudioProcessing() {\n",
    "        rtc::scoped_refptr<AudioProcessing> apm = AudioProcessingBuilder().Create();\n",
    "        apm->AddRef();\n",
    "        return apm.get();\n",
    "    }\n",
    "\n",
    "    void FFM_FreeAudioProcessing(FFM_AudioProcessing apm) {\n",
    "        if (apm) {\n",
    "            static_cast<AudioProcessing*>(apm)->Release();\n",
    "        }\n",
    "    }\n",
    "\n",
    "    void FFM_ApplyAudioProcessingConfig(FFM_AudioProcessing apm,\n",
    "        bool ns_enabled, int ns_level,\n",
    "        bool aec_enabled, bool aec_hp_filter,\n",
    "        bool hp_enabled,\n",
    "        bool gc_enabled, int gc_fixed_gain_db,\n",
    "        bool agc_enabled, int agc_target_level, int agc_max_gain, int agc_max_noise, int agc_step) {\n",
    "\n",
    "        AudioProcessing* ap = static_cast<AudioProcessing*>(apm);\n",
    "        AudioProcessing::Config config = ap->GetConfig();\n",
    "\n",
    "        config.noise_suppression.enabled = ns_enabled;\n",
    "        config.noise_suppression.level = static_cast<AudioProcessing::Config::NoiseSuppression::Level>(ns_level);\n",
    "\n",
    "        config.echo_canceller.enabled = aec_enabled;\n",
    "        config.echo_canceller.enforce_high_pass_filtering = aec_hp_filter;\n",
    "\n",
    "        config.high_pass_filter.enabled = hp_enabled;\n",
    "\n",
    "        config.gain_controller1.enabled = gc_enabled || agc_enabled;\n",
    "        if (gc_enabled && !agc_enabled) {\n",
    "            config.gain_controller1.mode = AudioProcessing::Config::GainController1::kFixedDigital;\n",
    "        } else if (agc_enabled) {\n",
    "            config.gain_controller1.mode = AudioProcessing::Config::GainController1::kAdaptiveDigital;\n",
    "        }\n",
    "\n",
    "        ap->ApplyConfig(config);\n",
    "    }\n",
    "\n",
    "    void FFM_SetStreamDelayMs(FFM_AudioProcessing apm, int delay_ms) {\n",
    "        static_cast<AudioProcessing*>(apm)->set_stream_delay_ms(delay_ms);\n",
    "    }\n",
    "\n",
    "    int FFM_ProcessStream(FFM_AudioProcessing apm, const int16_t* src, int sample_rate_in, int channels, int16_t* dest) {\n",
    "        AudioProcessing* ap = static_cast<AudioProcessing*>(apm);\n",
    "        StreamConfig config(sample_rate_in, channels);\n",
    "        memcpy(dest, src, config.num_frames() * channels * sizeof(int16_t));\n",
    "        return ap->ProcessStream(dest, config, config, dest);\n",
    "    }\n",
    "\n",
    "    FFM_Vad FFM_CreateVad() {\n",
    "        VadInst* vad = WebRtcVad_Create();\n",
    "        return vad;\n",
    "    }\n",
    "\n",
    "    void FFM_FreeVad(FFM_Vad vad) {\n",
    "        if (vad) WebRtcVad_Free(static_cast<VadInst*>(vad));\n",
    "    }\n",
    "\n",
    "    int FFM_InitVad(FFM_Vad vad) {\n",
    "        return WebRtcVad_Init(static_cast<VadInst*>(vad));\n",
    "    }\n",
    "\n",
    "    int FFM_SetVadMode(FFM_Vad vad, int mode) {\n",
    "        return WebRtcVad_set_mode(static_cast<VadInst*>(vad), mode);\n",
    "    }\n",
    "\n",
    "    int FFM_ProcessVad(FFM_Vad vad, int sample_rate, const int16_t* audio_frame, size_t frame_length) {\n",
    "        return WebRtcVad_Process(static_cast<VadInst*>(vad), sample_rate, audio_frame, frame_length);\n",
    "    }\n",
    "\n",
    "    FFM_Resampler FFM_CreateResampler() {\n",
    "        return new PushResampler<int16_t>();\n",
    "    }\n",
    "\n",
    "    void FFM_FreeResampler(FFM_Resampler resampler) {\n",
    "        if (resampler) delete static_cast<PushResampler<int16_t>*>(resampler);\n",
    "    }\n",
    "\n",
    "    int FFM_Resample(FFM_Resampler resampler, const int16_t* src, size_t src_length, int src_rate, int16_t* dest, size_t dest_capacity, int dest_rate, int channels) {\n",
    "        PushResampler<int16_t>* r = static_cast<PushResampler<int16_t>*>(resampler);\n",
    "        r->InitializeIfNeeded(src_rate, dest_rate, channels);\n",
    "        return r->Resample(src, src_length, dest, dest_capacity);\n",
    "    }\n",
    "\n",
    "    }\n",
    "    \"\"\")\n",
    "\n",
    "with open(os.path.join(wrapper_dir, \"webrtc_ffm.cc\"), \"w\") as f:\n",
    "    f.write(cpp_content)"
   ],
   "id": "783ae2bb67b1ce1b"
  },
  {
   "metadata": {},
   "cell_type": "code",
   "outputs": [],
   "execution_count": null,
   "source": [
    "build_gn_content = textwrap.dedent(\"\"\"\\\n",
    "    import(\"//webrtc.gni\")\n",
    "\n",
    "    shared_library(\"webrtc_ffm\") {\n",
    "      sources = [\n",
    "        \"webrtc_ffm.cc\",\n",
    "        \"webrtc_ffm.h\",\n",
    "      ]\n",
    "      deps = [\n",
    "        \"//modules/audio_processing:audio_processing\",\n",
    "        \"//common_audio:common_audio\",\n",
    "        \"//api/audio:audio_frame_api\",\n",
    "      ]\n",
    "    }\n",
    "    \"\"\")\n",
    "\n",
    "with open(os.path.join(wrapper_dir, \"BUILD.gn\"), \"w\") as f:\n",
    "    f.write(build_gn_content)"
   ],
   "id": "677e50857d1919b2"
  },
  {
   "metadata": {},
   "cell_type": "code",
   "outputs": [],
   "execution_count": null,
   "source": [
    "root_build_gn = os.path.join(webrtc_src_dir, \"BUILD.gn\")\n",
    "with open(root_build_gn, \"a\") as f:\n",
    "    f.write(\"\\n\")\n",
    "    f.write(\"group(\\\"ffm_build\\\") {\\n\")\n",
    "    f.write(\"  deps = [ \\\"//ffm_wrapper:webrtc_ffm\\\" ]\\n\")\n",
    "    f.write(\"}\\n\")"
   ],
   "id": "b855f25b3af90d3e"
  }
 ],
 "metadata": {},
 "nbformat": 4,
 "nbformat_minor": 5
}
